import "./globals.css";

import type { Metadata } from "next";
import localFont from "next/font/local";
import { NextIntlClientProvider } from "next-intl";

import Header from "../../components/header";

const pretendardFont = localFont({
  src: "../../public/fonts/PretendardVariable.woff2",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
type Props = {
  children: React.ReactNode;
};

export default async function RootLayout({ children }: Props) {
  return (
    <html lang="en" className="overflow-y-scroll">
      <body
        className={`relative size-full antialiased ${pretendardFont.className}`}
      >
        <NextIntlClientProvider>
          <Header />
          <main className="pt-16">{children}</main>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
